planning_pipelines:
  ompl:
    request_adapters: default_planner_request_adapters/AddTimeParameterization default_planner_request_adapters/FixWorkspaceBounds default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints
    start_state_max_bounds_error: 0.1
    planning_plugin: ompl_interface/OMPLPlanner
    planner_configs:
      RRT:
        type: geometric::RRT
        range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
        goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
      RRTConnect:
        type: geometric::RRTConnect
        range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
      RRTstar:
        type: geometric::RRTstar
        range: 0.0  # Max motion added to tree. ==> maxDistance_ default: 0.0, if 0.0, set on setup()
        goal_bias: 0.05  # When close to goal select goal, with this probability? default: 0.05
        delay_collision_checking: 1  # Stop collision checking as soon as C-free parent found. default 1

    manipulator:
      default_planner_config: RRTConnect
      planner_configs:
        - RRT
        - RRTConnect
        - RRTstar
